services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ma_base
      MYSQL_USER: ulysse
      MYSQL_PASSWORD: motdepasse
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  mysql-data:
